# Active sections on the website to deactivate comment out with '#'
# you can also change order here and it will reflect on page
Sections:
  - ueber
  - ort
  - programm
  - referenten
  - registrierung
  - atf
  - kosten
  - kontakt
# Titles which you can translate to other languages
Titles:
  ueber: "Über"
  ort: "Veranstaltungsort"
  referenten: "Referenten"
  programm: "Programm"
  registrierung: Registrierung
  atf: ATF-Anerkennung
  kosten: "Kosten"
  kontakt: "Kontakt"
# The Call To Action button at the header,
# If you don't want this, just remove the callToAction property.
CallToAction:
  text: "Registrieren Sie sich jetzt!"
  link: "#registrierung"

# Das gesamte Programm
Schedule:
  - name: "Ankunft der Teilnehmer"
    time: "bis 9:00"
  - name: ""
    photo: "/img/joshua-hirneiss.png"
    bio: "Biografische Daten"
    company: "Geschäftsführer Urban GmbH"
    link:
      href: "http://www.urbanonline.de"
      text: "Geschäftsführer Urban GmbH & Co. KG"
    presentation:
      title: "Joshua Hirneiß"
      description: "Begrüßung der Teilnehmer"
      time: "9:00 bis 9:15"
  - name: ""
    photo: "/img/theresa-scheu.jpg"
    bio: "Dr. Theresa Scheu ist Fachtierärztin für Rinder auf dem Lehr- und Versuchsgut Neumühle (Pfalz) "
    link:
      href: "https://www.hofgut-neumuehle.de/"
      text: "Fachtierärztin für Rinder"
    presentation:
      title: "Dr. Theresa Scheu"
      description: "Ergebnisse und Erfahrungen von Untersuchungen mit Kälbern am Tränkeautomaten auf dem Hofgut Neumühle"
      time: "9:15 bis 10:15"
  - name: "Pause"
    time: "10:15 bis 10:30"
  - name: ""
    photo: "/img/andre-effmert.jpg"
    bio: "Andre Effmert ist Fachberater für Kälbergesundheit und der Leiter des Schulungszentrums der Firma Urban"
    company: "Urban GmbH & Co. KG"
    link:
      href: "http://www.urbanonline.de"
      text: "Fachberater Kälbergesundheit"
    presentation:
      title: "Andre Effmert"
      description: "Fallstricke am Tränkeautomaten: Fehler erkennen"
      time: "10:30 bis 11:45"
  - name: ""
    photo: "/img/andre-effmert.jpg"
    bio: "Andre Effmert ist Fachberater für Kälbergesundheit und der Leiter des Schulungszentrums der Firma Urban"
    company: "Urban GmbH & Co. KG"
    link:
      href: "http://www.urbanonline.de"
      text: "Fachberater Kälbergesundheit"
    presentation:
      title: "Andre Effmert"
      description: "Praktische Übungen am Tränkeautomaten zur Fehlererkennung"
      time: "11:45 bis 12:30"
  - name: "Mittagessen"
    time: "12:30 bis 13:30 "
  - name: ""
    photo: "/img/regina-deininger.png"
    bio: "Dr. Theresa Scheu ist Fachtierärztin für Rinder auf dem Lehr- und Versuchsgut Neumühle (Pfalz)"
    company: "Lehr- und Versuchsgut Neumühle, Urban GmbH & Co. KG"
    link:
      href: "http://github.com/stevie"
      text: ""
    presentation:
      title: "Dr. Theresa Scheu, Regina Deininger"
      description: "UV-C zur Desinfektion in der Stallumgebung, effektiv oder Hokuspokus?"
      time: "13:30 bis 15:00"
  - name: "Kaffeepause"
    time: "15:00 bis 15:15"
  - name: ""
    photo: "/img/speakers.png"
    bio: "Praktische Übungen/ Fragen und Antworten"
    company: ""
    link:
      href: ""
      text: ""
    presentation:
      title: "Alle Dozenten"
      description: "Praktische Übungen/ Fragen und Antworten"
      time: "15:00 bis 16:15"
  - name: ""
    photo: "/img/andreas-deininger.jpg"
    bio: "Dr. Andreas Deininger ist Leiter des Produktmanagements der Firma Urban GmbH & Co. KG"
    company: "Urban GmbH & Co.KG"
    link:
      href: "http://www.urbanonline.de"
      text: "Leiter Produktmanagement"
    presentation:
      title: "Dr. Andreas Deininger"
      description: "Schlussworte, Zusammenfassung der Veranstaltung "
      time: "16:15 bis 16:30 "
  - name: "Ende der Veranstaltung"
    time: "16:30"
        
